### ISSUE TITLE
Repository name should be react-native-100ms

### ISSUE THREAD

**Issue by paramaggarwal** [100mslive/react-native-hms#141]
Typically the naming of RN libraries has the `react-native-` prefix.

**Comment by ygit** [comment]
Thanks for pointing @paramaggarwal 
We'll take it up

**Comment by ygit** [comment]
@paramaggarwal WE have updated the repository name as well. The library was already `@100mslive/react-native-hms`

**Comment by paramaggarwal** [comment]
oh yeah, makes sense 👍
