### ISSUE TITLE
library not installed react-native-hms

### ISSUE THREAD

**Issue by noddy1996** [100mslive/react-native-hms#147]
i am trying to install this library using `npm install react-native-hms` but its giving me an error `No valid versions available for react-native-hms`

![image](https://user-images.githubusercontent.com/46047333/131957475-1df9874d-66b8-4710-b5f8-0e50ae9fc890.png)

and then i was trying using yarn `yarn add  react-native-hms`. its giving me another error
![image](https://user-images.githubusercontent.com/46047333/131957655-0a8e11d2-477b-4f51-aba8-aa5d722e9534.png)

please help me if you have solution.

**Comment by Akarsh08** [comment]
try running `npm i @100mslive/react-native-hms --save`

**Comment by ygit** [comment]
@eramudeep try running `npm i @100mslive/react-native-hms --save`

**Comment by ygit** [comment]
@noddy1996 @eramudeep were you able to resolve this issue?

**Comment by ygit** [comment]
@noddy1996 @eramudeep I hope you were able to integrate the package. Closing this issue, let us know if you need any other help in integrating.
