### ISSUE TITLE
Make react-native-web compatible

### ISSUE THREAD

**Issue by tylerssn** [100mslive/react-native-hms#185]
So far no other similar library supports web & native. It would be a huge value add.

If the developer workflow is documented, I'd be open to contributing.

**Comment by ygit** [comment]
hi @tylerssn 

we have React version for the web: https://docs.100ms.live/javascript/v2/guides/react-quickstart

We have not picked up React Native for Web yet. Very much welcome your contributions.

We can get on a call if you want to know more about the developer workflow, we'll document it soon.

**Comment by ygit** [comment]
@Akarsh08 Can you check how feasible this is?
