### ISSUE TITLE
React Native ios: Change role of peer 'selector' not working as expected

### ISSUE THREAD

**Issue by ronit100ms** [100mslive/react-native-hms#419]
RN ios:
Change role of peer
Scroll not working as expected
Although role is changed
but scroll is not working as expected

**Comment by ronit100ms** [comment]
This issue is happening wherever there is a selector option(scroller returns back to the top)

**Comment by ronit100ms** [comment]
tested on 1.31.0(41)
still facing same issue

**Comment by samarthjain10** [comment]
The PR with this issue's fix was raised today. It will be fixed in the upcoming build
