### ISSUE TITLE
Screen Share from RN: not smooth, getting stuck

### ISSUE THREAD

**Issue by ronit100ms** [100mslive/react-native-hms#522]
When Screen share is on
Sometimes the screen freezes and recovers after 3 sec
Not a smooth experience for other peers

**Comment by ygit** [comment]
@ronit100ms Do add a screen recording video  if possible

**Comment by ronit100ms** [comment]
https://user-images.githubusercontent.com/93121334/151815980-6beba332-8d7f-480f-a872-605678ad55f6.mp4
