### ISSUE TITLE
React Native fixes needed

### ISSUE THREAD

**Issue by sankar2389** [100mslive/react-native-hms#62]
error Cannot find module 'metro-config/src/defaults/blacklist'

Fix
const blacklist = require('metro-config/src/defaults/exclusionList');

error: Error: Unable to resolve module ../screens/Home 

Fix
Rename the /screens/home.js to Home.js

But still ended up continuous errors while trying to run the example project. Is there any working version available?

**Comment by ygit** [comment]
@sankar2389 These has been fixed in the latest version of the [Example app](https://github.com/100mslive/100ms-react-native/tree/main/example). Try it out & let us know your experience

**Comment by ygit** [comment]
@sankar2389 were you able to resolve this issue?

**Comment by sankar2389** [comment]
Moved Native method instead
