### ISSUE TITLE
Expo managed app?

### ISSUE THREAD

**Issue by b0iq** [100mslive/react-native-hms#645]
Hello there,

I have question. Can we use this library with expo managed app?

becuase what I know is that if the package contain native SDK cannot be integrated with expo managed app. And I have project that I'm planning for; will depend on this library so much. 

Cheers!

**Comment by ygit** [comment]
@b0iq Our SDK is supported for integration in Expo-managed apps. Please follow the steps mentioned here: 
https://www.100ms.live/docs/react-native/v2/features/integration#expo-setup
