### ISSUE TITLE
Add support for React Native 0.70.0 & above versions

### ISSUE THREAD

**Issue by ygit** [100mslive/react-native-hms#745]
Refer: https://github.com/facebook/react-native/releases/tag/v0.70.0

**Comment by aphillipo** [comment]
Okay does this not currently work?

**Comment by ygit** [comment]
@aphillipo We have not done testing for 0.70.0+ versions yet. 
Currently, our Example app deliberately runs on 0.64.x version, so that our major clientele support is maintained.
This ticket is for tracking that we first test out the package thoroughly on 0.70.0+
