### ISSUE TITLE
Browser Recording producing recording file with multiple on off sessions 

### ISSUE THREAD

**Issue by amitbravo** [100mslive/react-native-hms#868]
considering Browser recording, assume, in a particular session , a host stop and on recording multiple times(say 4 times in 1 hr meeting), would it create one final mp4 or would there be 4 mp4s in my s3 bucket ?

**Comment by ygit** [comment]
@amitbravo  There will be 4 different recordings as there is no option to pause.

**Comment by amitbravo** [comment]
under my test , I had 2 participants A and B. In a given session, first A recorded video for 10 secs around, then B did for 5 seconds , I have found only one video of duration: 157 e.g. which is I think 157/10 = 15.7 second long.

**Comment by anujdharwar** [comment]
@amitbravo, there is no option to pause the browser recording so every time you stop the recording, one file is created and gets added to your bucket. You would be getting 4 separate recordings in the first scenario you mentioned. Can you share the room id where you found a single recording even after starting and stopping the recording multiple times?

I'll take a look at the logs to identify what happened.

**Comment by anujdharwar** [comment]
@amitbravo - can you share the room id with me?

**Comment by ygit** [comment]
hey @amitbravo 
As discussed over Discord, this issue has been resolved.
