### ISSUE TITLE
App close by swiping does not let a user out from the room

### ISSUE THREAD

**Issue by amitbravo** [100mslive/react-native-hms#869]
If A and B users are in the group , B closes the app swiping it out  , room still show and A and B and if B joins again, there are now 2 B's in the room .how can I solve it ?

**Comment by ygit** [comment]
@amitbravo You can call `leave` function by listening to the App Lifecycle event. If `leave` room is not invoked & the app is killed then the peer is kept in Room for 60 seconds before removing it completely.

**Comment by amitKsp25** [comment]
can we alter this time e.g. 20 seconds ?

**Comment by ygit** [comment]
No @amitKsp25 
To prevent multiple B's within the same room you can add user identification in your app.

**Comment by ygit** [comment]
hey @amitKsp25 
Closing this issue. Contact us for further inquiries or concerns.
