### ISSUE TITLE
recorded video display black tiles only

### ISSUE THREAD

**Issue by amitbravo** [100mslive/react-native-hms#872]
sometimes recorded video showing only black titles, using 0.9.0 version. sometimes recording misses entirely .

**Comment by ygit** [comment]
@amitbravo Can you share more details about this issue?
Also, I'd recommend joining our Discord channel: https://100ms.live/discord

**Comment by ygit** [comment]
hey @amitbravo 
Closing this issue. Contact us for further inquiries or concerns.
