### ISSUE TITLE
Recorded video time noted with Beam yet no video in the list found 

### ISSUE THREAD

**Issue by amitbravo** [100mslive/react-native-hms#873]
I started video and record session for few mins , when call api e.g. https://api.100ms.live/v2/sessions?room_id=63c287f8247e0716e063efb3 got results as follows, however, no video in the list. 
using 0.9.0 version
aws s3 setup fine , sometimes video comes up , sometimes not . 
{
    "limit": 10,
    "data": [
        {
            "id": "63c28880d5b3e3a6fe2f3d47",
            "room_id": "63c287f8247e0716e063efb3",
            "customer_id": "620f2cff71bd215ae0422c27",
            "app_id": "620f2cff71bd215ae0422c28",
            "active": false,
            "peers": {
                "8b7ed914-3f50-485b-ab08-0c7176b4e8a8": {
                    "id": "8b7ed914-3f50-485b-ab08-0c7176b4e8a8",
                    "session_id": "63c28880d5b3e3a6fe2f3d47",
                    "name": "Andrew",
                    "role": "host",
                    "user_id": "620f2cff71bd215ae0422c26",
                    "joined_at": "2023-01-14T10:48:32.018Z",
                    "left_at": "2023-01-14T10:54:00.085Z",
                    "user": "620f2cff71bd215ae0422c26"
                },
                "ce1abb64-86ac-4865-a737-e1910314d7d0": {
                    "id": "ce1abb64-86ac-4865-a737-e1910314d7d0",
                    "session_id": "63c28880d5b3e3a6fe2f3d47",
                    "name": "Beam",
                    "role": "host",
                    "user_id": "6a36f289-655d-4bfb-9ad9-46c7ba51e5f5",
                    "joined_at": "2023-01-14T10:48:39.95Z",
                    "left_at": "2023-01-14T10:51:53.041Z",
                    "user": "6a36f289-655d-4bfb-9ad9-46c7ba51e5f5"
                }
            },
            "created_at": "2023-01-14T10:48:32.02Z",
            "updated_at": "2023-01-14T10:54:00.219Z",
            "_id": "63c28880d5b3e3a6fe2f3d47"
        }
    ],
    "last": "63c28880d5b3e3a6fe2f3d47"
}

**Comment by ygit** [comment]
hey @amitbravo 
As discussed over Discord, this issue has been resolved.
