### ISSUE TITLE
iOS `PiP` Support

### ISSUE THREAD

**Issue by b0iq** [100mslive/react-native-hms#950]
I was wondering when the pip support is planned. I need this feature to be enabled in my current project is there's any workaround to enable it? 

Only manually be just leaving the app to display PiP.

**Comment by ygit** [comment]
hey @b0iq 

If you are looking for iOS PIP Mode support while playing Live Streaming HLS content, then that's already available.

PIP support for iOS Video Calls is on our roadmap but its release timelines are not scheduled currently.
